config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "top#index"
  get "about" => "top#about" , as: "about"
  get "bad_request" => "top#bad_request"
  get "forbidden" => "top#forbidden"
  get "internal_server_error" => "top#internal_server_error"
  
  1.upto(18) do |n|
    get "lesson/step#{n}(/:name)" => "lesson#step#{n}"
  end
  resources :members do
    get "search" , on: :collection
    resources :entries, only: [:index]
  end
  resource :session, only: [:create, :destroy]
  resource :account, only: [:show, :edit, :update]
  resource :password, only: [:show, :edit, :update]
  resources :articles
  resources :entries do
    patch "like", "unlike", on: :member
    get "voted", on: :collection
  end
end

app/views/shared/_errors.html.erb
<% if obj.errors.present? %>
  <div class="errors">
    <h3>エラーがあります</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<%= link_to "このサイトについて", :about %>
Coryright ©<%= link_to "Oiax Inc", "htpp://www.oiax.co.jp/" %>

app/views/shared/_header.html.erb
<%= image_tag "logo.gif", size:"272×48", alt:"Morning Glory" %>

<% if current_member %>
  <ul class="account-menu">
    <%= link_to current_member.name + "さん" , :account %>
    <%= menu_link_to "ログアウト", :session, method: :delete, data: {confirm: "ログアウトしますか？"} %>
  </ul>
<% end %>
<nav class="menubar">
  <ul>
    <%= menu_link_to "TOP", :root %>
    <%= menu_link_to "ニュース", :articles %>
    <%= menu_link_to  "ブログ", :entries %>
    <% if current_member %>
    <%= menu_link_to "会員名簿", members_path %>
    <%= menu_link_to "管理ページ", "#" %>
    <% end %>
  </ul>
</nav>

app/views/shared/_login.html.erb
<h2>ログイン</h2>
<% if flash.alert %><p class="alert" ><%= flash.alert %></p><% end %>
<%= form_tag :session, id:"login_form" do %>
  <div>
    <label>ユーザー名：</label>
    <input type="text" name ="name">
  </div>
  <div>
    <label>パスワード</label>
    <input type="password" name="password">
  </div>
  <div>
    <input type="submit" value="ログイン" >
  </div>
<% end %>

app/views/shared/_member_form.html.erb
<%= render "shared/errors" , obj: @member %>
<table class="attr">
  <tr>
    <th><%= f.label :new_profile_picture %></th>
    <td><%= f.file_field :new_profile_picture %></td>
  </tr>
  <tr>
    <th><%= f.label :number %></th>
    <td><%= f.text_field :number, size:8%></td>
  </tr>
  <tr>
    <th><%= f.label :name  %></th>
    <td><%= f.text_field :name %></td>
  </tr>
  <tr>
    <th><%= f.label :full_name  %></th>
    <td><%= f.text_field :full_name %></td>
  </tr>
  <tr>
    <th><%= Member.human_attribute_name(:sex) %></th>
    <td>
      <%= f.radio_button :sex, 1 %>
      <%= f.label :sex_1 %>
      <%= f.radio_button :sex, 2 %>
      <%= f.label :sex_2 %>
    </td>
  </tr>
  <tr>
    <th><%= f.label :birthday, 
        for: "member_birthday_1i" %></th>
    <td><%= f.date_select :birthday,
        start_year: 1940, end_year: Time.current.year,
        use_month_numbers: true %></td>
  </tr>
  <tr>
    <th><%= f.label :email  %></th>
    <td><%= f.text_field :email %></td>
  </tr>
  <% if @member.new_record? %>
    <tr>
      <th><%= f.label :password, "パスワード" %></th>
      <th><%= f.text_field :password %></th>
    </tr>
  <% end %>
  <% if controller.kind_of?(MembersController) %>
    <tr>
      <th>
        <%= Member.human_attribute_name(:administrator) %>
      </th>
      <td>
        <%= f.check_box :administrator,
          disabled: !current_member.administrator? %>
        <%= f.label :administrator %>
      </td>
    </tr>
  <% end %>
  </table>

app/views/shared/_sidebar.html.erb
<%= render "shared/login" unless current_member %>

<h2>最新ニュース</h2>
<% 
  articles = Article.visible.order(released_at: :desc).limit(5)
  articles = articles.open_to_the_public unless current_member
%>
<ul>
  <% articles.each do |article| %>
  <li><%= link_to article.title , article %></li>
  <% end %>
</ul>
<h2>会員のブログ</h2>
  <%
    entries = Entry.readable_for(current_member)
      .order(posted_at: :desc).limit(5)
  %>
<ul>
  <% entries.each do |entry| %>
    <li>
      <%= link_to entry.title , entry %>
      by <%= link_to entry.author.name, [entry.author, :entries] %>
    </li>
  <% end %>
</ul>