config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "top#index"
  get "about" => "top#about" , as: "about"
  get "bad_request" => "top#bad_request"
  get "forbidden" => "top#forbidden"
  get "internal_server_error" => "top#internal_server_error"
  
  1.upto(18) do |n|
    get "lesson/step#{n}(/:name)" => "lesson#step#{n}"
  end
  resources :members do
    get "search" , on: :collection
    resources :entries, only: [:index]
  end
  resource :session, only: [:create, :destroy]
  resource :account, only: [:show, :edit, :update]
  resource :password, only: [:show, :edit, :update]
  resources :articles
  resources :entries do
    patch "like", "unlike", on: :member
    get "voted", on: :collection
  end
end

app/models/member.rb
class Member < ApplicationRecord
  has_secure_password

  has_many :entries, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :voted_entries, through: :votes, source: :entry
  has_one_attached :profile_picture
  attribute :new_profile_picture
  validates :number, presence: true,
    numericality: {
      only_integer: true,
      greater_than: 0,
      less_than: 100,
      allow_blank: true
    },
    uniqueness: true
  validates :name, presence: true,
    format: {
      with: /\A[A-Za-z][A-Za-z0-9]*\z/,
      allow_blank: true,
      message: :invalid_member_name
    },
    length: { minimum: 2, maximum: 20, allow_blank: true },
    uniqueness: { case_sensitive: false }
  validates :full_name, presence: true, length: { maximum: 20 }
  validates :email, email: { allow_blank: true }

  attr_accessor :current_password
  validates :password, presence: {if: :current_password}

  before_save do
    if new_profile_picture
      self.profile_picture = new_profile_picture
    end
  end

  def votable_for?(entry)
    entry && entry.author != self && !votes.exists?(entry_id: entry.id)
  end

  class << self
    def search(query)
      rel = order("number")
      if query.present?
        rel = rel.where("name LIKE ? OR full_name LIKE ?",
          "%#{query}%", "%#{query}%")
      end
      rel
    end
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :login_required

  # 会員一覧
  def index
    @members = Member.order("number")
      .page(params[:page]).per(15)
  end

  # 検索
  def search
    @members = Member.search(params[:q])
      .page(params[:page]).per(15)

    render "index"
  end

  # 会員情報の詳細
  def show
    @member = Member.find(params[:id])
  end

  # 新規作成フォーム
  def new
    @member = Member.new(birthday: Date.new(1980, 1, 1))
  end

  # 更新フォーム
  def edit
    @member = Member.find(params[:id])
  end

  # 会員の新規登録
  def create
    @member = Member.new(member_params)
    if @member.save
      redirect_to @member, notice: "会員を登録しました。"
    else
      render "new"
    end
  end

  # 会員情報の更新
  def update
    @member = Member.find(params[:id])
    @member.assign_attributes(member_params)
    if @member.save
      redirect_to @member, notice: "会員情報を更新しました。"
    else
      render "edit"
    end
  end

  # 会員の削除
  def destroy
    @member = Member.find(params[:id])
    @member.destroy
    redirect_to :members, notice: "会員を削除しました。"
  end

  # ストロング・パラメータ
  private def member_params
    attrs = [
      :new_profile_picture,
      :remove_profile_picture,
      :number,
      :name,
      :full_name,
      :gender,
      :birthday,
      :email,
      :administrator
    ]

    attrs << :password if action_name == "create"

    params.require(:member).permit(attrs)
  end
end

app/views/members/_body.html.erb
<table class="attr">
  <tr>
    <th>プロフィール画像</th>
    <td>
      <% if @member.profile_picture.attached? %>
        <%= image_tag @member.profile_picture.variant(resize: "128x128") %>
      <% end %>
    </td>
  </tr>
  <tr>
    <th width="150">背番号</th>
    <td><%= @member.number %></td>
  </tr>
  <tr>
    <th>ユーザー名</th>
    <td><%= @member.name %></td>
  </tr>
  <tr>
    <th>氏名</th>
    <td><%= @member.full_name %></td>
  </tr>
  <tr>
    <th>性別</th>
    <td><%= @member.sex == 1 ? "男" : "女" %></td>
  </tr>
  <tr>
    <th>誕生日</th>
    <td><%= @member.birthday&.strftime("%Y年%m月%d日") %></td>
  </tr>
  <tr>
    <th>メールアドレス</th>
    <td><%= @member.email %></td>
  </tr>
  <tr>
    <th>管理者</th>
    <td><%= @member.administrator? ? "○" : "－" %></td>
  </tr>
</table>

app/views/members/edit.html.erb
<% @page_title = "会員情報の編集" %>

<h1><%= @page_title %></h1>

<div class="toolbar"><%= link_to "会員の詳細に戻る", @member %></div>

<%= form_for(@member) do |f| %>
  <%= render "shared/member_form", f:f %>
  <div><%= f.submit %></div>
<% end %>

app/views/members/index.html.erb
<%= @page_title = "会員名簿"%>
<h1><%= @page_title %></h1>

<%= form_tag :search_members, method: :get, class:"search" do %>
  <%= text_field_tag "q", params[:q] %>
  <%= submit_tag "検索" %>
<% end %>

<div class="toolbar"><%= link_to "会員の新規登録", new_member_path %></div>

<% if @members.present? %>
  <table class="list">
    <thead>
      <tr>
        <th>背番号</th>
        <th>ユーザー名</th>
        <th>氏名</th>
        <th>操作</th>
      </tr>
    </thead>
    <tbody>
    <% @members.each do |member| %>
      <tr>
        <td style="text-align: right"><%= member.number %></td>
        <td><%= link_to member.name , member_path(member.id) %></td>
        <td><%= member.full_name %></td>
        <td>
          <%= link_to "編集", edit_member_path(member.id) %> | 
          <%= link_to "削除", member_path(member.id) , method: :delete , data:{confirm: "本当に削除しますか？"} %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <%= paginate @members %>
<% else %>
  <p>会員情報がありません</p>
<% end %>

app/views/members/new.html.erb
<% @page_title = "会員の新規登録" %>

<h1><%= @page_title %></h1>

<%= form_for(@member) do |f| %>
  <%= render "shared/member_form", f:f %>
  <div><%= f.submit %></div>
<% end %>

app/views/members/show.html.erb
<% @page_title = "会員の詳細" %>
<h1><%= @page_title %></h1>
<div class="toolbar">
  <%= link_to "編集" , edit_member_path(@member) %>
</div>


<%= render "members/body" %>